package com.supertech.superbatch.plant.enums;

public enum EquipmentType {

    TEMPERATURE_TRANSMITTER,
    PRESSURE_TRANSMITTER,
    FLOW_TRANSMITTER,
    LEVEL_TRANSMITTER,

    TEMPERATURE_CONTROLLER,
    PRESSURE_CONTROLLER,
    FLOW_CONTROLLER,
    LEVEL_CONTROLLER,

    VALVE,
    CONTROL_VALVE,

    PH_ANALYZER,
    CONDUCTIVITY_ANALYZER,
    DENSITY_METER,

    SWITCH,
    LIMIT_SWITCH,
    PROXIMITY_SENSOR,

    ANALOG_INPUT,
    ANALOG_OUTPUT,
    DIGITAL_INPUT,
    DIGITAL_OUTPUT
}