create table
    action (
        id bigint generated by default as identity,
        name varchar(100) not null,
        can_delete boolean not null default true,
        constraint pk_action primary key (id),
        constraint uk_action_name unique (name)
    );


create table
    area(
        id bigint generated by default as identity,
        plant_id bigint not null,
        name varchar(100) not null,
        description varchar(500),
        area_type varchar(50) not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_area primary key (id),
        constraint uk_area_plant_name unique (plant_id, name)
    );


create table
    batch (
        id bigint generated by default as identity,
        batch_no varchar(50) not null,
        master_recipe_id bigint not null,
        control_recipe_id bigint,
        unit_id bigint not null,
        start_date_time timestamp(6),
        end_date_time timestamp(6),
        status varchar(30) not null check (
            status in ('TRANSFERRED', 'READY', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'ABORTED')
        ),
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_batch primary key (id),
        constraint uk_batch_batch_no unique (batch_no)
    );


create table
    batch_sop (
        id bigint generated by default as identity,
        batch_id bigint not null,
        step_no integer not null,
        action_id bigint not null,
        transition_id bigint not null,
        from_equipment_id bigint,
        to_equipment_id bigint,
        std_time double precision,
        act_time double precision,
        start_date_time timestamp(6),
        end_date_time timestamp(6),
        message varchar(500),
        constraint pk_batch_sop primary key (id),
        constraint uk_batch_step unique (batch_id, step_no)
    );


create table
    batch_sop_material (
        id bigint generated by default as identity,
        batchsop_id bigint not null,
        material_id bigint not null,
        std_qty double precision,
        act_qty double precision,
        constraint pk_batch_sop_material primary key (id),
        constraint uk_batch_sop_material unique (batchsop_id, material_id)
    );


create table
    batch_sop_parameter (
        id bigint generated by default as identity,
        batchsop_id bigint not null,
        parameter_id bigint not null,
        std_value double precision,
        act_value double precision,
        constraint pk_batch_sop_parameter primary key (id),
        constraint uk_batch_sop_parameter unique (batchsop_id, parameter_id)
    );


create table
    batch_audit (
        id bigint generated by default as identity,
        entity smallint not null check (entity between 0 and 14),
        module_id bigint not null,
        performed_by_id bigint not null,
        action varchar(20) not null check (action in ('CREATED', 'UPDATED', 'DELETED')),
        performed_at timestamp(6) not null,
        old_data text,
        new_data text,
        constraint pk_batch_audit primary key (id)
    );


create table
    control_recipe_sop (
        id bigint generated by default as identity,
        control_recipe_id bigint not null,
        step_no integer not null,
        action_id bigint not null,
        transition_id bigint not null,
        from_equipment_id bigint,
        to_equipment_id bigint,
        std_time double precision,
        message varchar(500),
        constraint pk_control_recipe_sop primary key (id),
        constraint uk_control_recipe_step unique (control_recipe_id, step_no)
    );


create table
    control_recipe_sop_material (
        id bigint generated by default as identity,
        control_recipesop_id bigint not null,
        material_id bigint not null,
        std_qty double precision,
        constraint pk_control_recipe_sop_material primary key (id),
        constraint uk_control_recipe_sop_material unique (control_recipesop_id, material_id)
    );


create table
    control_recipe_sop_parameter (
        id bigint generated by default as identity,
        control_recipesop_id bigint not null,
        parameter_id bigint not null,
        std_value double precision,
        constraint pk_control_recipe_sop_parameter primary key (id),
        constraint uk_control_recipe_sop_parameter unique (control_recipesop_id, parameter_id)
    );


create table
    control_recipe (
        id bigint generated by default as identity,
        recipe_id bigint not null,
        unit_id bigint not null,
        created_by_id bigint not null,
        shift_incharge_id bigint,
        name varchar(100) not null,
        batch_no varchar(50) not null,
        batch_size integer not null,
        status varchar(20) not null check (status in ('SCHEDULED', 'TRANSFERRED')),
        scheduled_at timestamp(6),
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_control_recipe primary key (id),
        constraint uk_control_recipe_batch_no unique (batch_no)
    );


create table
    equipment (
        id bigint generated by default as identity,
        creator_unit_id bigint not null,
        code varchar(50) not null,
        name varchar(100) not null,
        description varchar(500),
        equipment_type varchar(20) not null check (equipment_type in ('MAIN_EQUIPMENT', 'SUB_EQUIPMENT')),
        capacity integer,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_equipment primary key (id),
        constraint uk_equipment_code unique (code)
    );


create table
    equipment_unit (
        equipment_id bigint not null,
        unit_id bigint not null,
        constraint pk_equipment_unit primary key (equipment_id, unit_id)
    );


create table
    license (
        id bigint generated by default as identity,
        license_key varchar(255) not null,
        machine_id varchar(100) not null,
        customer_name varchar(100) not null,
        company_name varchar(100) not null,
        plan varchar(20) not null check (plan in ('TRIAL', 'PROFESSIONAL', 'ENTERPRISE')),
        status varchar(20) not null check (status in ('NOT_ACTIVATED', 'ACTIVE', 'EXPIRED', 'INVALID', 'SUSPENDED')),
        version varchar(20),
        max_clients integer not null,
        activated_at timestamp(6) not null,
        expiry_date DATE not null,
        last_validated_at timestamp(6),
        constraint pk_license primary key (id),
        constraint uk_license_key unique (license_key)
    );


create table
    material (
        id bigint generated by default as identity,
        code varchar(50) not null,
        name varchar(100) not null,
        description varchar(500),
        material_type varchar(30) not null check (material_type in ('RAW_MATERIAL', 'FINISHED_PRODUCT')),
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_material primary key (id),
        constraint uk_material_code unique (code)
    );


create table
    message (
        id bigint generated by default as identity,
        name varchar(255) not null,
        constraint pk_message primary key (id),
        constraint uk_message_name unique (name)
    );


create table
    module (
        id bigint not null,
        name varchar(100) not null,
        constraint pk_module primary key (id),
        constraint uk_module_name unique (name)
    );


create table
    parameter (
        id bigint generated by default as identity,
        name varchar(100) not null,
        uom varchar(30) not null check (
            uom in (
                'CELSIUS',
                'BAR',
                'PSI',
                'LITER',
                'KG',
                'RPM',
                'PERCENT',
                'LITER_PER_MINUTE',
                'KG_PER_HOUR',
                'PH',
                'VOLT',
                'AMPERE'
            )
        ),
        constraint pk_parameter primary key (id),
        constraint uk_parameter_name unique (name)
    );


create table
    permission (
        id bigint generated by default as identity,
        role_id bigint not null,
        module_id bigint not null,
        access boolean not null default false,
        constraint pk_permission primary key (id),
        constraint uk_role_module unique (role_id, module_id)
    );


create table
    plant (
        id bigint generated by default as identity,
        name varchar(100) not null,
        description varchar(500),
        location varchar(255),
        plant_type varchar(50) not null,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_plant primary key (id),
        constraint uk_plant_name unique (name)
    );


create table
    recipe (
        id bigint generated by default as identity,
        name varchar(100) not null,
        description varchar(500),
        material_id bigint not null,
        unit_id bigint not null,
        created_by bigint not null,
        batch_size integer not null,
        status varchar(20) not null check (status in ('RELEASED', 'UNRELEASED')),
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_recipe primary key (id),
        constraint uk_recipe_name unique (name)
    );


create table
    recipe_sop (
        id bigint generated by default as identity,
        recipe_id bigint not null,
        step_no integer not null,
        action_id bigint not null,
        transition_id bigint not null,
        from_equipment_id bigint,
        to_equipment_id bigint,
        std_time double precision,
        message varchar(500),
        constraint pk_recipe_sop primary key (id),
        constraint uk_recipe_step unique (recipe_id, step_no)
    );


create table
    recipe_sop_material (
        id bigint generated by default as identity,
        recipesop_id bigint not null,
        material_id bigint not null,
        std_qty double precision,
        constraint pk_recipe_sop_material primary key (id),
        constraint uk_recipe_sop_material unique (recipesop_id, material_id)
    );


create table
    recipe_sop_parameter (
        id bigint generated by default as identity,
        recipesop_id bigint not null,
        parameter_id bigint not null,
        std_value double precision,
        constraint pk_recipe_sop_parameter primary key (id),
        constraint uk_recipe_sop_parameter unique (recipesop_id, parameter_id)
    );


create table
    role (
        id bigint generated by default as identity,
        name varchar(100) not null,
        description varchar(500),
        system_role boolean not null default false,
        deleted boolean not null default false,
        deleted_at timestamp(6),
        deleted_by_id bigint,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_role primary key (id),
        constraint uk_role_name unique (name)
    );


create table
    transition (
        id bigint generated by default as identity,
        name varchar(100) not null,
        can_delete boolean not null default true,
        constraint pk_transition primary key (id),
        constraint uk_transition_name unique (name)
    );


create table
    unit (
        id bigint generated by default as identity,
        area_id bigint not null,
        code varchar(50) not null,
        name varchar(100) not null,
        description varchar(500),
        capacity integer,
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_unit primary key (id),
        constraint uk_unit_code unique (code),
        constraint uk_unit_area_name unique (area_id, name)
    );


create table
    users (
        id bigint generated by default as identity,
        role_id bigint not null,
        name varchar(100) not null,
        email varchar(255) not null,
        password varchar(255) not null,
        system_account boolean not null default false,
        password_change_required boolean not null default false,
        deleted boolean not null default false,
        deleted_at timestamp(6),
        deleted_by_id bigint,
        created_by_id bigint,
        last_login_at timestamp(6),
        created_at timestamp(6) not null,
        updated_at timestamp(6),
        constraint pk_users primary key (id)
    );


alter table area
add constraint fk_area_plant foreign key (plant_id) references plant (id);


alter table batch
add constraint fk_batch_control_recipe foreign key (control_recipe_id) references control_recipe (id);


alter table batch
add constraint fk_batch_recipe foreign key (master_recipe_id) references recipe (id);


alter table batch
add constraint fk_batch_unit foreign key (unit_id) references unit (id);


alter table batch_sop
add constraint fk_batch_sop_action foreign key (action_id) references action (id);


alter table batch_sop
add constraint fk_batch_sop_batch foreign key (batch_id) references batch (id);


alter table batch_sop
add constraint fk_batch_sop_from_equipment foreign key (from_equipment_id) references equipment (id);


alter table batch_sop
add constraint fk_batch_sop_to_equipment foreign key (to_equipment_id) references equipment (id);


alter table batch_sop
add constraint fk_batch_sop_transition foreign key (transition_id) references transition (id);


alter table batch_sop_material
add constraint fk_batch_sop_material_batch_sop foreign key (batchsop_id) references batch_sop (id);


alter table batch_sop_material
add constraint fk_batch_sop_material_material foreign key (material_id) references material (id);


alter table batch_sop_parameter
add constraint fk_batch_sop_parameter_batch_sop foreign key (batchsop_id) references batch_sop (id);


alter table batch_sop_parameter
add constraint fk_batch_sop_parameter_parameter foreign key (parameter_id) references parameter (id);


alter table batch_audit
add constraint fk_batch_audit_module foreign key (module_id) references module (id);


alter table batch_audit
add constraint fk_batch_audit_performed_by foreign key (performed_by_id) references users (id);


alter table control_recipe
add constraint fk_control_recipe_created_by foreign key (created_by_id) references users (id);


alter table control_recipe
add constraint fk_control_recipe_recipe foreign key (recipe_id) references recipe (id);


alter table control_recipe
add constraint fk_control_recipe_shift_incharge foreign key (shift_incharge_id) references users (id);


alter table control_recipe
add constraint fk_control_recipe_unit foreign key (unit_id) references unit (id);


alter table control_recipe_sop
add constraint fk_control_recipe_sop_action foreign key (action_id) references action (id);


alter table control_recipe_sop
add constraint fk_control_recipe_sop_control_recipe foreign key (control_recipe_id) references control_recipe (id);


alter table control_recipe_sop
add constraint fk_control_recipe_sop_from_equipment foreign key (from_equipment_id) references equipment (id);


alter table control_recipe_sop
add constraint fk_control_recipe_sop_to_equipment foreign key (to_equipment_id) references equipment (id);


alter table control_recipe_sop
add constraint fk_control_recipe_sop_transition foreign key (transition_id) references transition (id);


alter table control_recipe_sop_material
add constraint fk_control_recipe_sop_material_control_recipe_sop foreign key (control_recipesop_id) references control_recipe_sop (id);


alter table control_recipe_sop_material
add constraint fk_control_recipe_sop_material_material foreign key (material_id) references material (id);


alter table control_recipe_sop_parameter
add constraint fk_control_recipe_sop_parameter_control_recipe_sop foreign key (control_recipesop_id) references control_recipe_sop (id);


alter table control_recipe_sop_parameter
add constraint fk_control_recipe_sop_parameter_parameter foreign key (parameter_id) references parameter (id);


alter table equipment
add constraint fk_equipment_creator_unit foreign key (creator_unit_id) references unit (id);


alter table equipment_unit
add constraint fk_equipment_unit_equipment foreign key (equipment_id) references equipment (id);


alter table equipment_unit
add constraint fk_equipment_unit_unit foreign key (unit_id) references unit (id);


alter table permission
add constraint fk_permission_module foreign key (module_id) references module (id);


alter table permission
add constraint fk_permission_role foreign key (role_id) references role (id);


alter table recipe
add constraint fk_recipe_created_by foreign key (created_by) references users (id);


alter table recipe
add constraint fk_recipe_material foreign key (material_id) references material (id);


alter table recipe
add constraint fk_recipe_unit foreign key (unit_id) references unit (id);


alter table recipe_sop
add constraint fk_recipe_sop_action foreign key (action_id) references action (id);


alter table recipe_sop
add constraint fk_recipe_sop_recipe foreign key (recipe_id) references recipe (id);


alter table recipe_sop
add constraint fk_recipe_sop_from_equipment foreign key (from_equipment_id) references equipment (id);


alter table recipe_sop
add constraint fk_recipe_sop_to_equipment foreign key (to_equipment_id) references equipment (id);


alter table recipe_sop
add constraint fk_recipe_sop_transition foreign key (transition_id) references transition (id);


alter table recipe_sop_material
add constraint fk_recipe_sop_material_recipe_sop foreign key (recipesop_id) references recipe_sop (id);


alter table recipe_sop_material
add constraint fk_recipe_sop_material_material foreign key (material_id) references material (id);


alter table recipe_sop_parameter
add constraint fk_recipe_sop_parameter_recipe_sop foreign key (recipesop_id) references recipe_sop (id);


alter table recipe_sop_parameter
add constraint fk_recipe_sop_parameter_parameter foreign key (parameter_id) references parameter (id);


alter table role
add constraint fk_role_deleted_by foreign key (deleted_by_id) references users (id);


alter table unit
add constraint fk_unit_area foreign key (area_id) references area(id);


alter table users
add constraint fk_users_created_by foreign key (created_by_id) references users (id);


alter table users
add constraint fk_users_deleted_by foreign key (deleted_by_id) references users (id);


alter table users
add constraint fk_users_role foreign key (role_id) references role (id);


create unique index uk_users_email_active on users (email)
where
    deleted = false;


create index idx_area_plant_id on area(plant_id);


create index idx_batch_master_recipe_id on batch (master_recipe_id);


create index idx_batch_control_recipe_id on batch (control_recipe_id);


create index idx_batch_unit_id on batch (unit_id);


create index idx_batch_sop_batch_id on batch_sop (batch_id);


create index idx_batch_sop_action_id on batch_sop (action_id);


create index idx_batch_sop_transition_id on batch_sop (transition_id);


create index idx_batch_sop_from_equipment_id on batch_sop (from_equipment_id);


create index idx_batch_sop_to_equipment_id on batch_sop (to_equipment_id);


create index idx_batch_sop_material_material_id on batch_sop_material (material_id);


create index idx_batch_sop_parameter_parameter_id on batch_sop_parameter (parameter_id);


create index idx_batch_audit_module_id on batch_audit (module_id);


create index idx_batch_audit_performed_by_id on batch_audit (performed_by_id);


create index idx_control_recipe_recipe_id on control_recipe (recipe_id);


create index idx_control_recipe_unit_id on control_recipe (unit_id);


create index idx_control_recipe_created_by_id on control_recipe (created_by_id);


create index idx_control_recipe_shift_incharge_id on control_recipe (shift_incharge_id);


create index idx_control_recipe_sop_control_recipe_id on control_recipe_sop (control_recipe_id);


create index idx_control_recipe_sop_action_id on control_recipe_sop (action_id);


create index idx_control_recipe_sop_transition_id on control_recipe_sop (transition_id);


create index idx_control_recipe_sop_from_equipment_id on control_recipe_sop (from_equipment_id);


create index idx_control_recipe_sop_to_equipment_id on control_recipe_sop (to_equipment_id);


create index idx_control_recipe_sop_material_material_id on control_recipe_sop_material (material_id);


create index idx_control_recipe_sop_parameter_parameter_id on control_recipe_sop_parameter (parameter_id);


create index idx_equipment_creator_unit_id on equipment (creator_unit_id);


create index idx_equipment_unit_unit_id on equipment_unit (unit_id);


create index idx_permission_module_id on permission (module_id);


create index idx_recipe_material_id on recipe (material_id);


create index idx_recipe_unit_id on recipe (unit_id);


create index idx_recipe_created_by on recipe (created_by);


create index idx_recipe_sop_recipe_id on recipe_sop (recipe_id);


create index idx_recipe_sop_action_id on recipe_sop (action_id);


create index idx_recipe_sop_transition_id on recipe_sop (transition_id);


create index idx_recipe_sop_from_equipment_id on recipe_sop (from_equipment_id);


create index idx_recipe_sop_to_equipment_id on recipe_sop (to_equipment_id);


create index idx_recipe_sop_material_material_id on recipe_sop_material (material_id);


create index idx_recipe_sop_parameter_parameter_id on recipe_sop_parameter (parameter_id);


create index idx_role_deleted_by_id on role (deleted_by_id);


create index idx_unit_area_id on unit (area_id);


create index idx_users_role_id on users (role_id);


create index idx_users_created_by_id on users (created_by_id);


create index idx_users_deleted_by_id on users (deleted_by_id);