# Server Info
spring.application.name=superbatch
server.port=8080
server.address=0.0.0.0

# Cors
cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/superbatch
spring.datasource.username=postgres
spring.datasource.password=root

# Create/update tables automatically
# spring.jpa.hibernate.ddl-auto=update
# See SQL in console
# spring.jpa.show-sql=true
# Pretty print SQL
# spring.jpa.properties.hibernate.format_sql=true

# Fly Way
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

# Schema Genration
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=schema.sql
# spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata

# Secret Key
jwt.secret=7e2f9d8c4b1a6f3fff9c1a7b5f2d8e6c
jwt.expiration=86400000

# Log
debug=false
logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.autoconfigure=WARN
logging.level.org.springdoc=WARN
logging.level.com.zaxxer.hikari=OFF
logging.level.org.hibernate=WARN
logging.level.org.hibernate.orm.query=ERROR
logging.level.org.apache=WARN
logging.level.org.springframework.security=OFF
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
logging.level.org.springframework.boot.devtools=OFF
spring.devtools.restart.enabled=true
spring.jpa.open-in-view=false
spring.main.banner-mode=off
logging.level.org.flywaydb=WARN
logging.level.org.springframework.jdbc=WARN

# Human readable console logs
logging.pattern.console=%d{HH:mm:ss} %msg%n
# Human readable file logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n

# File logging
logging.file.name=C:/ProgramData/SuperBatch/logs/superbatch.log

# Rotate every 5MB
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB
logging.logback.rollingpolicy.file-name-pattern=C:/ProgramData/SuperBatch/logs/superbatch-%d{yyyy-MM-dd}.%i.log

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized

# Application information
management.info.env.enabled=true

info.app.name=SuperBatch
info.app.description=SuperBatch Batch Management System
info.app.version=1.0.0

license.server.base-url=http://192.168.1.126:8081
license.validation.interval=3600000
license.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnrAnCKRTPo37G6zCXFZj86BIq//bkP3PpMqXGf16seps5wzkXGCvoYxvdhbQTVd5Etf7CSis3BIfOpXTity/24Ei9TitEThVjNxoauc9fAXGbh07zWaFBhg2bz2rgwFlL3wyYPx2LbrLyR6J5lBUuvpZEm7LVvoQysB9iYc5lVXofVdyE2zEgXO2o2vuxXqlbKj8pPJnpLgRRTcfg8L3VYHG/+vYIwA+g2WYUw/x9aLtKhSUVVeP3qoizzGwiJCfp3QxY6nT7CMzT2ssPMD6wygemadn3sKQ+dofIEyeHvEV9Y3W201TGvepvMKJeFuMdXSC3SbhLuP5Hj+edDMrlwIDAQAB
