# APP
spring.application.name=superbatch

# SQL JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/superbatch
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# Log
logging.level.root=INFO
logging.level.com.mvp.jobportal=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.apache=WARN
logging.level.org.springframework.security=OFF
logging.level.org.springframework.boot.autoconfigure=ERROR
spring.output.ansi.enabled=ALWAYS
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
logging.level.com.zaxxer.hikari=INFO
spring.jpa.open-in-view=false
spring.main.banner-mode=off

jwt.secret=12345678901234567890123456789012345678901234567890
jwt.expiration=86400000